#!/usr/bin/env python3
"""
Make7Segment.py

Generate an SVG preview and simple CNC G-code outline for a single 7-segment digit.

Usage:
  python Make7Segment.py --height 200 --width 120 --stroke 20 --radius 10

Outputs: Make7Segment_H{height}_W{width}.svg and .gcode in the current directory.

Note: This script produces simple outline toolpaths (no advanced CAM features).
Use at your own risk and inspect G-code before running on a machine.
"""
import sys
import math
import argparse
from xml.sax.saxutils import escape

try:
    from PIL import Image, ImageDraw
    _HAS_PIL = True
except Exception:
    Image = None
    ImageDraw = None
    _HAS_PIL = False


def fr(x):
    return f"{x:.3f}"


# No external image dependency: this script only writes SVG and G-code now.

def rect_svg(x, y, w, h, rx, fill="none", stroke="#000", stroke_width=1):
    return f'<rect x="{fr(x)}" y="{fr(y)}" width="{fr(w)}" height="{fr(h)}" rx="{fr(rx)}" fill="{fill}" stroke="{stroke}" stroke-width="{fr(stroke_width)}" />\n'


def write_svg(filename, W, H, segments, margin=10, show_board=False, board_w=None, board_h=None, render_source='poly'):
    vw = W + 2 * margin
    vh = H + 2 * margin
    with open(filename, "w") as f:
        f.write('<?xml version="1.0" encoding="UTF-8"?>\n')
        f.write(f'<svg xmlns="http://www.w3.org/2000/svg" width="{fr(vw)}mm" height="{fr(vh)}mm" viewBox="0 0 {fr(vw)} {fr(vh)}">\n')
        f.write('<g transform="translate(%s,%s)">\n' % (fr(margin), fr(margin)))
        # background
        f.write(rect_svg(0, 0, W, H, 0, fill="#fff", stroke="#888", stroke_width=0.5))
        # Optionally draw the board perimeter (as a dashed rectangle) for demo inspection.
        if show_board and (board_w is not None) and (board_h is not None):
            # center digit in board: compute top-left offset of board relative to digit origin
            off_x = -((board_w - W) / 2.0)
            off_y = -((board_h - H) / 2.0)
            f.write(f'<rect x="{fr(off_x)}" y="{fr(off_y)}" width="{fr(board_w)}" height="{fr(board_h)}" fill="none" stroke="#080" stroke-width="0.8" stroke-dasharray="6,4" />\n')

        for seg in segments:
            poly = seg.get('poly')
            if render_source == 'poly' and poly:
                pts = " ".join([f"{fr(x)},{fr(y)}" for (x, y) in poly])
                f.write(f'<polygon points="{escape(pts)}" fill="#111" stroke="#000" stroke-width="0.5" />\n')
            else:
                f.write(rect_svg(seg['x'], seg['y'], seg['w'], seg['h'], seg.get('r',0), fill="#ffcccc", stroke="#800" , stroke_width=0.8))
        f.write('</g>\n')
        f.write('</svg>\n')


def write_gcode(filename, W, H, segments, bit_dia=3.0, cut_depth=3.0, pass_depth=1.5, feed=800, plunge=300, safe_z=5.0, show_board=False, board_w=None, board_h=None, margin=10):
    # Simple outline cut: plunge at segment corner, follow rounded-rectangle perimeter (polygon approximation).
    with open(filename, "w") as f:
        f.write("(Simple 7-seg outline generated by Make7Segment.py)\n")
        f.write("G21 (mm)\nG90 (absolute)\nG17\n")
        # Optionally embed board dimension comments for user inspection
        if show_board and (board_w is not None) and (board_h is not None):
            f.write(f"(Board size: {board_w:.3f} mm x {board_h:.3f} mm, margin {margin} mm)\n")
            f.write("(Digit centered on board — demo only, not for production)\n")
            f.write("(Demo mode: single pass used for board/digit preview)\n")
        f.write(f"F{feed}\n")
        z = 0.0
        depth = cut_depth
        passes = max(1, int(math.ceil(depth / pass_depth)))
        pass_step = depth / passes
        for i in range(passes):
            cur_depth = -(i + 1) * pass_step
            f.write(f"(pass {i+1}/{passes} to Z{fr(cur_depth)})\n")
            for seg in segments:
                poly = seg.get('poly')
                if not poly:
                    # fallback to simple rect
                    x0 = seg['x']
                    y0 = seg['y']
                    w = seg['w']
                    h = seg['h']
                    poly = [(x0, y0), (x0+w, y0), (x0+w, y0+h), (x0, y0+h)]
                # rapid to first point
                f.write(f"G0 Z{fr(safe_z)}\n")
                f.write(f"G0 X{fr(poly[0][0])} Y{fr(poly[0][1])}\n")
                f.write(f"G1 Z{fr(cur_depth)} F{plunge}\n")
                for (cx, cy) in poly[1:]+[poly[0]]:
                    f.write(f"G1 X{fr(cx)} Y{fr(cy)} F{feed}\n")
                f.write(f"G0 Z{fr(safe_z)}\n")
        f.write("M5\nG0 X0 Y0\n")

        # Optionally include a cutting path for the full board perimeter (demo only)
        if show_board and (board_w is not None) and (board_h is not None):
            # Center the digit on the board: compute top-left offset of board relative to digit origin
            off_x = -((board_w - W) / 2.0)
            off_y = -((board_h - H) / 2.0)
            bp = [(off_x, off_y), (off_x + board_w, off_y), (off_x + board_w, off_y + board_h), (off_x, off_y + board_h)]
            # single pass at full depth for demo
            f.write(f"(Board perimeter demo cut)\n")
            f.write(f"G0 Z{fr(safe_z)}\n")
            f.write(f"G0 X{fr(bp[0][0])} Y{fr(bp[0][1])}\n")
            f.write(f"G1 Z{fr(-depth)} F{plunge}\n")
            for (cx, cy) in bp[1:]+[bp[0]]:
                f.write(f"G1 X{fr(cx)} Y{fr(cy)} F{feed}\n")
            f.write(f"G0 Z{fr(safe_z)}\n")


def make_segments(W, H, t, r, gap=None, overlap=0.0, hgap=0.0):
    # spacing: gap between segments. If gap is None use default t*0.5
    s = gap if (gap is not None) else (t * 0.5)
    ov = max(0.0, float(overlap))
    # hgap: how much to push A down and D up (and used later to shift verticals)
    hg = float(hgap) if (hgap is not None) else 0.0
    # extend horizontal length by overlap to close chamfer gaps
    Lh = W - 2*t + 2.0 * ov
    if Lh <= 0:
        raise ValueError("Computed invalid segment dimensions; check stroke vs overall size.")

    # Use segment A as vertical reference and place D symmetrically.
    segments = []
    # Keep a base A position for vertical segment reference, then move A
    # polygon down by hgap without changing the original top-vertical start
    base_Ay = s
    Ay = base_Ay + 1.0 * hg
    # base_Dy is the original top position for D (before shifting)
    base_Dy = H - s - t
    # move D polygon up by hg
    Dy = base_Dy - hg

    # A bottom and original D top
    A_bottom = Ay + t
    D_top_orig = base_Dy
    if D_top_orig <= A_bottom + 0.001:
        raise ValueError("Not enough vertical space for middle segment; reduce stroke or margins.")

    # center between A bottom and the shifted D top (G is not moved)
    center_mid = (A_bottom + Dy) / 2.0
    Gy = center_mid - (t / 2.0)
    # Use the middle of G as reference for hgap offsets.
    # G_mid is the center Y of the middle segment G.
    G_mid = Gy + (t / 2.0)
    hg = float(hgap)
    # Top verticals (F,B) will end at G_mid - hg; keep their start at the
    # original A bottom (so moving A polygon down does not shorten F/B).
    orig_A_bottom = base_Ay + t
    top_end = G_mid - hg
    Lv_top = top_end - orig_A_bottom
    if Lv_top < 0:
        Lv_top = 0.0
    top_vert_y = orig_A_bottom
    # Bottom verticals (E,C) will start at G_mid + hg
    bot_vert_y = G_mid + hg
    # compute bottom vertical length using the original D top so E/C keep length
    Lv_bot = D_top_orig - bot_vert_y
    if Lv_bot < 0:
        Lv_bot = 0.0

    # Horizontal segment A
    segments.append({'name':'A', 'x': (W - Lh)/2.0, 'y': Ay, 'w': Lh, 'h': t, 'r': r})

    # top verticals F and B already computed above (Lv_top)
    Fx = (W - Lh)/2.0 - (t/2.0)
    Bx = (W + Lh)/2.0 - (t/2.0)
    segments.append({'name':'F', 'x': Fx, 'y': top_vert_y, 'w': t, 'h': Lv_top, 'r': r})
    segments.append({'name':'B', 'x': Bx, 'y': top_vert_y, 'w': t, 'h': Lv_top, 'r': r})

    # middle horizontal G centered between A bottom and D top
    segments.append({'name':'G', 'x': (W - Lh)/2.0, 'y': Gy, 'w': Lh, 'h': t, 'r': r})

    # bottom verticals E and C already computed above (Lv_bot)
    segments.append({'name':'E', 'x': Fx, 'y': bot_vert_y, 'w': t, 'h': Lv_bot, 'r': r})
    segments.append({'name':'C', 'x': Bx, 'y': bot_vert_y, 'w': t, 'h': Lv_bot, 'r': r})

    # bottom horizontal D
    segments.append({'name':'D', 'x': (W - Lh)/2.0, 'y': Dy, 'w': Lh, 'h': t, 'r': r})

    return segments


def parse_args():
    p = argparse.ArgumentParser()
    p.add_argument('--height', type=float, default=200.0, help='digit height in mm')
    p.add_argument('--width', type=float, default=120.0, help='digit width in mm')
    p.add_argument('--stroke', type=float, default=20.0, help='segment thickness in mm')
    p.add_argument('--radius', type=float, default=10.0, help='corner radius in mm')
    p.add_argument('--bit', type=float, default=3.0, help='cutter diameter in mm')
    p.add_argument('--depth', type=float, default=None, help='cut depth in mm (overridden by --board-thickness)')
    p.add_argument('--passdepth', type=float, default=None, help='depth per pass in mm (overridden by --board-thickness and --cutting-paths)')
    p.add_argument('--board-thickness', type=float, default=12.0, help='total board thickness in mm (used as cut depth by default)')
    p.add_argument('--cutting-paths', type=int, default=4, help='number of depth passes to cut through the board')
    p.add_argument('--board-height', type=float, default=240.0, help='physical wooden board height in mm (default used when not specifying full board size)')
    p.add_argument('--board-width', type=float, default=None, help='physical wooden board width in mm (if omitted it will be calculated from digit width + margins)')
    p.add_argument('--show-board-dim', action='store_true', default=False, help='embed board dimension comments into the generated G-code and use a single demo pass')
    p.add_argument('--outprefix', type=str, default=None, help='output file prefix')
    p.add_argument('--gap', type=float, default=0.0, help='inter-segment gap in mm (overrides default t*0.5)')
    p.add_argument('--overlap', type=float, default=0.0, help='positive value to let segments overlap (mm) to close chamfer gaps')
    p.add_argument('--hgap', type=float, default=5.0, help='vertical shift for vertical segments: move F/B down by hgap and E/C up by hgap (mm)')
    # legacy: simple --gap still supported
    p.add_argument('--render-source', choices=['poly','rect'], default='poly', help='Render SVG/WEBP from chamfer polygons (poly) or from rectangular segment params (rect)')
    return p.parse_args()


def main():
    args = parse_args()
    H = args.height
    W = args.width
    t = args.stroke
    r = args.radius
    segments = make_segments(W, H, t, r, gap=args.gap, overlap=args.overlap, hgap=args.hgap)
    # Precompute chamfered polygon for each segment (use 'r' as chamfer distance)
    for seg in segments:
        seg['poly'] = chamfer_rect_points(seg['x'], seg['y'], seg['w'], seg['h'], seg.get('r', 0))
    prefix = args.outprefix or f"Make7Segment_H{int(H)}_W{int(W)}"
    svgfn = prefix + ".svg"
    gfn = prefix + ".gcode"
    print(f"Preparing outputs {svgfn} and {gfn} with H={H} W={W} t={t} r={r}")
    # Determine cut depth and per-pass depth. Prefer explicit --depth/--passdepth when provided,
    # otherwise use --board-thickness split into --cutting-paths passes.
    if args.depth is not None:
        cut_depth = float(args.depth)
    else:
        cut_depth = float(args.board_thickness)
    if args.passdepth is not None:
        pass_depth = float(args.passdepth)
        paths = max(1, int(math.ceil(cut_depth / pass_depth)))
    else:
        paths = max(1, int(args.cutting_paths))
        pass_depth = float(cut_depth) / float(paths)

    # Compute board dimensions (SVG margin used by write_svg default)
    margin = 10
    # board height: prefer explicit board_height argument, otherwise default from CLI
    board_h = float(args.board_height)
    # board width: if user provided use it, otherwise compute from digit width + 2*margin
    if args.board_width is not None:
        board_w = float(args.board_width)
    else:
        board_w = W + 2.0 * margin

    # Validate board is large enough to contain the digit including margins
    min_board_h = H + 2.0 * margin
    min_board_w = W + 2.0 * margin
    if board_h < min_board_h - 1e-6:
        print(f"Warning: provided board height {board_h:.3f} mm is smaller than required minimum {min_board_h:.3f} mm to contain the digit with margins.")
    if board_w < min_board_w - 1e-6:
        print(f"Warning: provided board width {board_w:.3f} mm is smaller than required minimum {min_board_w:.3f} mm to contain the digit with margins.")

    # Show both board and digit dimensions to the user
    print(f"\nBoard dimension (WxH): {board_w:.3f} mm x {board_h:.3f} mm (margin {margin} mm)")
    print(f"Digit dimension (WxH): {W:.3f} mm x {H:.3f} mm")

    # Print a concise summary so the user understands the cutting passes
    print(f"Board thickness: {cut_depth:.3f} mm")
    print(f"Number of passes: {paths}")
    print(f"Depth per pass: {pass_depth:.3f} mm")
    print("Pass targets (cumulative Z):")
    for i in range(paths):
        cum_z = -((i + 1) * pass_depth)
        print(f"  - Pass {i+1}: Z = {cum_z:.3f} mm")

    # If user requested to show board dimensions in G-code, force a single demo pass
    if args.show_board_dim:
        pass_depth = float(cut_depth)
        print("\nshow-board-dim enabled: using single demo pass for G-code preview")
        print("Updated Number of passes: 1")
    # Now write SVG (with optional board perimeter) and G-code
    write_svg(svgfn, W, H, segments, margin=margin, show_board=args.show_board_dim, board_w=board_w, board_h=board_h, render_source=args.render_source)
    write_gcode(gfn, W, H, segments, bit_dia=args.bit, cut_depth=cut_depth, pass_depth=pass_depth, show_board=args.show_board_dim, board_w=board_w, board_h=board_h, margin=margin)
    # Optionally write a raster preview using Pillow
    if _HAS_PIL:
        imgfn = prefix + ".webp"
        try:
            write_image(imgfn, W, H, segments, margin=margin, render_source=args.render_source)
            print(f"Wrote image: {imgfn}")
        except Exception as e:
            print("Image export failed:", e)

    print("Done.")




def rounded_rect_points(x, y, w, h, r, steps_per_corner=6):
    # Deprecated: replaced by chamfered polygon generator
    if r <= 0:
        return [(x, y), (x+w, y), (x+w, y+h), (x, y+h)]
    return chamfer_rect_points(x, y, w, h, r)


def chamfer_rect_points(x, y, w, h, c):
    # Return polygon points for a rectangle with chamfered (beveled) corners.
    # c is chamfer distance from each corner along edges.
    c = min(c, w/2.0, h/2.0)
    pts = []
    pts.append((x + c, y))
    pts.append((x + w - c, y))
    pts.append((x + w, y + c))
    pts.append((x + w, y + h - c))
    pts.append((x + w - c, y + h))
    pts.append((x + c, y + h))
    pts.append((x, y + h - c))
    pts.append((x, y + c))
    return pts


def write_image(filename, W, H, segments, margin=10, scale=8, bg=(255,255,255), segcolor=(0,0,0), render_source='poly'):
    if not _HAS_PIL:
        raise RuntimeError('Pillow not available; install with pip install pillow to generate webp image')
    px_w = int((W + 2*margin) * scale)
    px_h = int((H + 2*margin) * scale)
    img = Image.new('RGB', (px_w, px_h), color=bg)
    draw = ImageDraw.Draw(img)
    # draw border
    border_rect = [margin*scale, margin*scale, (margin+W)*scale, (margin+H)*scale]
    draw.rectangle(border_rect, outline=(0,0,0), width=max(2, int(scale/2)))
    for seg in segments:
        poly = seg.get('poly')
        if render_source == 'poly' and poly:
            pts_scaled = [((margin + x) * scale, (margin + y) * scale) for (x, y) in poly]
            draw.polygon(pts_scaled, fill=segcolor)
        else:
            x = (margin + seg['x']) * scale
            y = (margin + seg['y']) * scale
            w = seg['w'] * scale
            h = seg['h'] * scale
            r = seg.get('r', 0) * scale
            # PIL expects box as [left, top, right, bottom]
            box = [x, y, x + w, y + h]
            try:
                draw.rounded_rectangle(box, radius=max(0, int(r)), fill=segcolor)
            except Exception:
                # fallback: draw polygon from rounded points
                pts = rounded_rect_points(seg['x'] + margin, seg['y'] + margin, seg['w'], seg['h'], seg.get('r', 0), steps_per_corner=6)
                pts_scaled = [(px*scale, py*scale) for (px, py) in pts]
                draw.polygon(pts_scaled, fill=segcolor)
    img.save(filename, format='WEBP')
    
if __name__ == '__main__':
    main()
