#!/usr/bin/env python3
"""
Make7Segment.py

Generate an SVG preview and simple CNC G-code outline for a single 7-segment digit.
"""
import math
import argparse
import os
import configparser

try:
    from PIL import Image, ImageDraw, ImageFont
    _HAS_PIL = True
except Exception:
    Image = None
    ImageDraw = None
    _HAS_PIL = False

try:
    from shapely.geometry import Polygon, box
    from shapely.ops import unary_union
    _HAS_SHAPELY = True
except Exception:
    Polygon = None
    unary_union = None
    box = None
    _HAS_SHAPELY = False


def fr(x):
    return f"{x:.3f}"


# Profile defaults populated at runtime by load_profile(); parse_args will
# consult PROFILE_DEFAULTS when choosing argument defaults. If no profile is
# present the dict remains empty and hard-coded defaults are used.
PROFILE_DEFAULTS = {}


def load_profile(path):
    """Read profile INI at `path` and return a dict of normalized arg defaults.

    Keys in the INI may use '-' or '_' and will be normalized to argparse dest
    names (underscores). Boolean values use configparser.getboolean.
    """
    if not path or not os.path.exists(path):
        return {}
    cfg = configparser.ConfigParser()
    cfg.read(path)
    if 'profile' not in cfg:
        return {}
    sec = cfg['profile']
    out = {}
    # mapping of arg name -> type converter for numeric/string values
    type_map = {
        'height': float,
        'width': float,
        'stroke': float,
        'radius': float,
        'bit': float,
        'depth': float,
        'passdepth': float,
        'board_thickness': float,
        'cutting_paths': int,
        'board_height': float,
        'board_width': float,
        'board_outline': str,
        'outprefix': str,
        'spindle_speed': int,
        'feed': float,
        'plunge': float,
        'gap': float,
        'overlap': float,
        'hgap': float,
        'vert_length': float,
        'hort_length': float,
        'render_source': str,
    }
    # keys that should be interpreted as booleans
    boolean_keys = set([
        'show_board_dim', 'debug_centers', 'allow_vertical_overlap', 'pause_after_seg', 'debug_gcode', 'use_shapely', 'no_shapely', 'rotate'
    ])

    for raw_key in sec:
        key = raw_key.replace('-', '_')
        raw = sec.get(raw_key)
        if raw is None:
            continue
        raw = raw.strip()
        if raw == '':
            continue
        try:
            if key in boolean_keys:
                val = cfg.getboolean('profile', raw_key)
            else:
                conv = type_map.get(key, str)
                val = conv(raw)
        except Exception:
            val = raw
        out[key] = val
    # capture free-form comment if present
    if 'comment' in sec:
        out['comment'] = sec.get('comment')
    return out


def rect_svg(x, y, w, h, rx, fill="none", stroke="#000", stroke_width=1):
    return f'<rect x="{fr(x)}" y="{fr(y)}" width="{fr(w)}" height="{fr(h)}" rx="{fr(rx)}" fill="{fill}" stroke="{stroke}" stroke-width="{fr(stroke_width)}" />\n'


def write_svg(filename, W, H, segments, margin=10, show_board=False, board_w=None, board_h=None, render_source='poly'):
    vw = W + 2 * margin
    vh = H + 2 * margin
    with open(filename, 'w') as f:
        f.write('<?xml version="1.0" encoding="UTF-8"?>\n')
        f.write(f'<svg xmlns="http://www.w3.org/2000/svg" width="{fr(vw)}mm" height="{fr(vh)}mm" viewBox="0 0 {fr(vw)} {fr(vh)}">\n')
        f.write('<g transform="translate(%s,%s)">\n' % (fr(margin), fr(margin)))
        f.write(rect_svg(0, 0, W, H, 0, fill="#fff", stroke="#888", stroke_width=0.5))
        if show_board and (board_w is not None) and (board_h is not None):
            off_x = -((board_w - W) / 2.0)
            off_y = -((board_h - H) / 2.0)
            f.write(f'<rect x="{fr(off_x)}" y="{fr(off_y)}" width="{fr(board_w)}" height="{fr(board_h)}" fill="none" stroke="#f00" stroke-width="0.8" stroke-dasharray="6,4" />\n')
        for seg in segments:
            poly = seg.get('poly')
            if render_source == 'poly' and poly:
                pts = ' '.join([f"{fr(x)},{fr(y)}" for (x, y) in poly])
                f.write(f'<polygon points="{pts}" fill="#111" stroke="#000" stroke-width="0.5" />\n')
            else:
                f.write(rect_svg(seg['x'], seg['y'], seg['w'], seg['h'], seg.get('r', 0), fill="#ffcccc", stroke="#800", stroke_width=0.8))
        f.write('</g>\n')
        f.write('</svg>\n')


def write_gcode(filename, W, H, segments, bit_dia=3.0, cut_depth=3.0, pass_depth=1.5, feed=800, plunge=300, safe_z=5.0, show_board=False, board_w=None, board_h=None, margin=10, rotate=False, spindle_speed=None, pause_after_segment=False, debug_gcode=False):
    with open(filename, 'w') as f:
        if debug_gcode:
            f.write('(Simple 7-seg outline generated by Make7Segment.py)\n')
        f.write('G21\nG90\nG17\n')
        if debug_gcode and show_board and (board_w is not None) and (board_h is not None):
            f.write(f"(Board size: {board_w:.3f} mm x {board_h:.3f} mm, margin {margin} mm)\n")
        # If pausing after each segment, we will start/stop the spindle per-segment.
        if spindle_speed is not None and (not pause_after_segment):
            f.write(f"M3 S{int(spindle_speed)}\n")
        f.write(f"F{feed}\n")
        # Determine cutting depth and pass plan. When showing board dims we
        # only generate a single shallow reference layer (demo) instead of
        # the full-depth multi-pass cut.
        if show_board and (board_w is not None) and (board_h is not None):
            # demo depth: shallow mark for reference (<= 0.5 mm and <= cut_depth)
            demo_depth = min(0.5, max(0.0, float(cut_depth)))
            depth = demo_depth
            passes = 1
            pass_step = depth
        else:
            depth = cut_depth
            passes = max(1, int(math.ceil(depth / pass_depth)))
            pass_step = depth / passes
        if rotate:
            def _tx(x, y):
                return (H - y, x)
            desired_start = _tx(0.0, H)
        else:
            def _tx(x, y):
                return (x, y)
            desired_start = (0.0, H)

        processed = []
        dsx, dsy = desired_start
        def _dist_sq(p):
            dx = p[0] - dsx
            dy = p[1] - dsy
            return dx * dx + dy * dy
        ox, oy = desired_start
        if show_board and (board_w is not None) and (board_h is not None):
            off_x = -((board_w - W) / 2.0)
            off_y = -((board_h - H) / 2.0)
            bp = [(off_x, off_y), (off_x + board_w, off_y), (off_x + board_w, off_y + board_h), (off_x, off_y + board_h)]
            if debug_gcode:
                f.write(f"(Board perimeter - single reference layer)\n")
                f.write(f"(Board size: {board_w:.3f} mm x {board_h:.3f} mm)\n")
            # draw perimeter at shallow demo depth (one pass)
            demo_depth = pass_step if passes == 1 else min(0.5, float(cut_depth))
            f.write(f"G0 Z{fr(safe_z)}\n")
            # also draw the digit bounding box (W x H) so relationship is visible
            dbp = [(0.0, 0.0), (W, 0.0), (W, H), (0.0, H)]
            if debug_gcode:
                f.write(f"(Digit bounding box - {W:.3f} x {H:.3f} mm)\n")
            f.write(f"G0 Z{fr(safe_z)}\n")
            dx0, dy0 = _tx(dbp[0][0], dbp[0][1])
            f.write(f"G0 X{fr(dx0)} Y{fr(dy0)}\n")
            f.write(f"G1 Z{fr(-min(0.5, demo_depth))} F{plunge}\n")
            for (cx, cy) in dbp[1:]+[dbp[0]]:
                rx, ry = _tx(cx, cy)
                f.write(f"G1 X{fr(rx)} Y{fr(ry)} F{feed}\n")
            f.write(f"G0 Z{fr(safe_z)}\n")
            # draw segment outlines as single shallow pass for reference
            for seg in segments:
                poly = seg.get('poly')
                if not poly:
                    if all(k in seg for k in ('x', 'y', 'w', 'h')):
                        poly = chamfer_rect_points(seg['x'], seg['y'], seg['w'], seg['h'], seg.get('r', 0))
                    else:
                        continue
                tx_pts = [_tx(x, y) for (x, y) in poly]
                if not tx_pts:
                    continue
                f.write(f"G0 Z{fr(safe_z)}\n")
                sx, sy = tx_pts[0]
                f.write(f"G0 X{fr(sx)} Y{fr(sy)}\n")
                f.write(f"G1 Z{fr(-min(0.5, demo_depth))} F{plunge}\n")
                for (px, py) in tx_pts[1:]+[tx_pts[0]]:
                    f.write(f"G1 X{fr(px)} Y{fr(py)} F{feed}\n")
                f.write(f"G0 Z{fr(safe_z)}\n")
            bx0, by0 = _tx(bp[0][0], bp[0][1])
            f.write(f"G0 X{fr(bx0)} Y{fr(by0)}\n")
            f.write(f"G1 Z{fr(-demo_depth)} F{plunge}\n")
            for (cx, cy) in bp[1:]+[bp[0]]:
                rx, ry = _tx(cx, cy)
                f.write(f"G1 X{fr(rx)} Y{fr(ry)} F{feed}\n")
            f.write(f"G0 Z{fr(safe_z)}\n")

            # draw simple dimension indicator lines for width and height
            # horizontal width line (above top edge)
            dim_gap = max(2.0, float(margin) * 0.2)
            wx1, wy = bp[0][0], bp[0][1] - dim_gap
            wx2 = bp[1][0]
            sx, sy = _tx(wx1, wy)
            ex, ey = _tx(wx2, wy)
            if debug_gcode:
                f.write(f"(Board width indicator W={board_w:.3f} mm)\n")
            f.write(f"G0 Z{fr(safe_z)}\nG0 X{fr(sx)} Y{fr(sy)}\n")
            f.write(f"G1 Z{fr(-min(0.3, demo_depth))} F{plunge}\n")
            f.write(f"G1 X{fr(ex)} Y{fr(ey)} F{feed}\n")
            f.write(f"G0 Z{fr(safe_z)}\n")

            # vertical height line (to the right of board)
            hx, hy1 = bp[1][0] + dim_gap, bp[1][1]
            hy2 = bp[2][1]
            sx, sy = _tx(hx, hy1)
            ex, ey = _tx(hx, hy2)
            if debug_gcode:
                f.write(f"(Board height indicator H={board_h:.3f} mm)\n")
            f.write(f"G0 Z{fr(safe_z)}\nG0 X{fr(sx)} Y{fr(sy)}\n")
            f.write(f"G1 Z{fr(-min(0.3, demo_depth))} F{plunge}\n")
            f.write(f"G1 X{fr(ex)} Y{fr(ey)} F{feed}\n")
            f.write(f"G0 Z{fr(safe_z)}\n")
        else:
            # Generate cutting paths for each segment polygon or rect when
            # not in "show board demo" mode. This emits rapid moves to the
            # start point, then performs the multi-pass profile cuts.
            for seg in segments:
                poly = seg.get('poly')
                if not poly:
                    # fallback to chamfered rectangle points for rect-style
                    if all(k in seg for k in ('x', 'y', 'w', 'h')):
                        poly = chamfer_rect_points(seg['x'], seg['y'], seg['w'], seg['h'], seg.get('r', 0))
                    else:
                        continue

                # apply rotation transform if requested
                tx_pts = [_tx(x, y) for (x, y) in poly]
                if not tx_pts:
                    continue

                # optionally start spindle per-segment when pause-after-seg is used
                if spindle_speed is not None and pause_after_segment:
                    f.write(f"M3 S{int(spindle_speed)}\n")

                # rapid to safe Z and start XY
                f.write(f"G0 Z{fr(safe_z)}\n")
                sx, sy = tx_pts[0]
                f.write(f"G0 X{fr(sx)} Y{fr(sy)}\n")

                # multi-pass cutting
                for pi in range(passes):
                    target_depth = -min((pi + 1) * pass_step, depth)
                    f.write(f"G1 Z{fr(target_depth)} F{plunge}\n")
                    # follow polygon perimeter
                    for (px, py) in tx_pts[1:] + [tx_pts[0]]:
                        f.write(f"G1 X{fr(px)} Y{fr(py)} F{feed}\n")
                    f.write(f"G0 Z{fr(safe_z)}\n")

                if pause_after_segment:
                    # stop spindle and pause for operator intervention
                    f.write("M5\n")
                    f.write(f"G0 Z{fr(safe_z)}\n")
                    f.write("M0\n")
                    # restart spindle when resuming next segment
                    if spindle_speed is not None:
                        f.write(f"M3 S{int(spindle_speed)}\n")
        # stop spindle and return to home
        f.write("M5\n")
        f.write(f"G0 Z{fr(safe_z)}\n")
        if debug_gcode:
            f.write("(Returning to machine HOME X0 Y0)\n")
        f.write("G0 X0 Y0\n")


def chamfer_rect_points(x, y, w, h, c):
    # Prevent chamfer collapsing to the exact centerline for very narrow
    # segments by ensuring c is strictly less than half the width when possible.
    eps = 1e-6
    max_c_by_width = w / 2.0
    if max_c_by_width > eps:
        max_c_by_width = max(0.0, max_c_by_width - eps)
    c = min(c, max_c_by_width, h/2.0)
    pts = []
    pts.append((x + c, y))
    pts.append((x + w - c, y))
    pts.append((x + w, y + c))
    pts.append((x + w, y + h - c))
    pts.append((x + w - c, y + h))
    pts.append((x + c, y + h))
    pts.append((x, y + h - c))
    pts.append((x, y + c))
    return pts


def make_segments(W, H, t, r, gap=None, overlap=0.0, hgap=0.0, vert_length=0.0, hort_length=None, allow_vertical_overlap=True):
    s = gap if (gap is not None) else (t * 0.5)
    ov = max(0.0, float(overlap))
    hg = float(hgap) if (hgap is not None) else 0.0
    if hort_length is not None:
        Lh = float(hort_length)
        if Lh <= 0.0:
            raise ValueError(f'Invalid --hort-length {Lh:.3f}; must be > 0.0')
    else:
        Lh = W - 2*t + 2.0 * ov
    if Lh <= 0:
        raise ValueError('Computed invalid segment dimensions; check stroke vs overall size.')

    base_Ay = s
    Ay = base_Ay + 1.0 * hg
    base_Dy = H - s - t
    Dy = base_Dy - hg

    A_center = Ay + (t / 2.0)
    D_center = Dy + (t / 2.0)
    A_bottom = Ay + t
    D_top = Dy
    if D_center <= A_center + 0.001:
        raise ValueError('Not enough vertical space for middle segment; reduce stroke or margins.')

    # Compute middle (G) segment position so it's centered between A and D
    center_mid = (A_center + D_center) / 2.0
    Gy = center_mid - (t / 2.0)
    G_center = Gy + (t / 2.0)
    G_top = Gy
    G_bottom = Gy + t

    # Default vertical length (preserve original length unless user overrides)
    # Compute a natural vertical length from remaining space: distribute the free
    # height (excluding three horizontals and outer margins) equally to the two
    # vertical segments.
    free_height = H - (3.0 * t) - (2.0 * s)
    default_vert_len = max(0.0, free_height / 2.0)

    # Top vertical segments (F/B) should be centered between A_bottom and G_top
    available_top = G_top - A_bottom
    # keep original/default vertical length unless it doesn't fit
    Lv_top = default_vert_len
    if (not allow_vertical_overlap) and (Lv_top > available_top):
        Lv_top = max(0.0, available_top)
    top_mid = A_bottom + (available_top / 2.0) if available_top > 0.0 else A_bottom
    top_vert_y = top_mid - (Lv_top / 2.0)
    mid_top_center = top_mid

    # Bottom vertical segments (E/C) should be centered between G_bottom and D_top
    available_bot = D_top - G_bottom
    Lv_bot = default_vert_len
    if (not allow_vertical_overlap) and (Lv_bot > available_bot):
        Lv_bot = max(0.0, available_bot)
    bot_mid = G_bottom + (available_bot / 2.0) if available_bot > 0.0 else G_bottom
    bot_vert_y = bot_mid - (Lv_bot / 2.0)
    mid_bot_center = bot_mid

    vl = float(vert_length) if (vert_length is not None) else 0.0
    if abs(vl) > 1e-12:
        # Interpretation (1): treat vert_length as an additive delta to the
        # vertical rectangle height `h`, keeping the vertical centerline fixed.
        # top_mid and bot_mid are the center Y positions for top/bottom verticals.
        top_mid = mid_top_center
        bot_mid = mid_bot_center

        Lv_top_new = Lv_top + vl
        Lv_bot_new = Lv_bot + vl
        # clamp to valid ranges
        if Lv_top_new < 0.0:
            Lv_top_new = 0.0
        if Lv_bot_new < 0.0:
            Lv_bot_new = 0.0
        if (not allow_vertical_overlap):
            max_top_len = max(0.0, available_top)
            if Lv_top_new > max_top_len:
                Lv_top_new = max_top_len
            max_bot_len = max(0.0, available_bot)
            if Lv_bot_new > max_bot_len:
                Lv_bot_new = max_bot_len

        # keep centerlines fixed: compute new top/bot y by centering new lengths
        top_vert_y = top_mid - (Lv_top_new / 2.0)
        bot_vert_y = bot_mid - (Lv_bot_new / 2.0)
        Lv_top = Lv_top_new
        Lv_bot = Lv_bot_new

    segments = []
    # A
    segments.append({'name':'A', 'x': (W - Lh)/2.0, 'y': Ay, 'w': Lh, 'h': t, 'r': r, 'center_y': A_center})
    Fx = (W - Lh)/2.0 - (t/2.0)
    Bx = (W + Lh)/2.0 - (t/2.0)
    top_vert_center = mid_top_center
    segments.append({'name':'F', 'x': Fx, 'y': top_vert_y, 'w': t, 'h': Lv_top, 'r': r, 'center_y': top_vert_center})
    segments.append({'name':'B', 'x': Bx, 'y': top_vert_y, 'w': t, 'h': Lv_top, 'r': r, 'center_y': top_vert_center})
    segments.append({'name':'G', 'x': (W - Lh)/2.0, 'y': Gy, 'w': Lh, 'h': t, 'r': r, 'center_y': G_center})
    bot_vert_center = mid_bot_center
    segments.append({'name':'E', 'x': Fx, 'y': bot_vert_y, 'w': t, 'h': Lv_bot, 'r': r, 'center_y': bot_vert_center})
    segments.append({'name':'C', 'x': Bx, 'y': bot_vert_y, 'w': t, 'h': Lv_bot, 'r': r, 'center_y': bot_vert_center})
    segments.append({'name':'D', 'x': (W - Lh)/2.0, 'y': Dy, 'w': Lh, 'h': t, 'r': r, 'center_y': D_center})
    return segments


def parse_args():
    p = argparse.ArgumentParser()
    def _d(key, fallback):
        return PROFILE_DEFAULTS.get(key, fallback)
    # allow specifying profile path; when omitted main() will attempt to use ./profile.cfg
    p.add_argument('--profile', type=str, default=None, help='Path to profile INI file. If omitted, uses ./profile.cfg when present.')
    p.add_argument('--height', type=float, default=_d('height', 120.0), help='digit height in mm')
    p.add_argument('--width', type=float, default=_d('width', 80.0), help='digit width in mm')
    p.add_argument('--stroke', type=float, default=_d('stroke', 16.0), help='segment thickness in mm')
    p.add_argument('--radius', type=float, default=_d('radius', 10.0), help='corner radius in mm')
    p.add_argument('--bit', type=float, default=_d('bit', 2.0), help='cutter diameter in mm')
    p.add_argument('--depth', type=float, default=_d('depth', None), help='cut depth in mm (overridden by --board-thickness)')
    p.add_argument('--passdepth', type=float, default=_d('passdepth', 0.5), help='depth per pass in mm (overridden by --board-thickness and --cutting-paths)')
    p.add_argument('--board-thickness', type=float, default=_d('board_thickness', 4.5), help='total board thickness in mm (used as cut depth by default)')
    p.add_argument('--cutting-paths', type=int, default=_d('cutting_paths', 10), help='number of depth passes to cut through the board')
    p.add_argument('--board-height', type=float, default=_d('board_height', 172.0), help='physical wooden board height in mm (default used when not specifying full board size)')
    p.add_argument('--board-width', type=float, default=_d('board_width', 100.0), help='physical wooden board width in mm (if omitted it will be calculated from digit width + margins)')
    p.add_argument('--show-board-dim', action='store_true', default=_d('show_board_dim', False), help='embed board dimension comments into the generated G-code and use a single demo pass')
    p.add_argument('--board-outline', choices=['solid','dashed'], default=_d('board_outline', 'dashed'), help='outline style for the board perimeter in the WEBP image')
    p.add_argument('--debug-centers', action='store_true', default=_d('debug_centers', True), help='draw center markers and reference lines in the WEBP for verification')
    p.add_argument('--outprefix', type=str, default=_d('outprefix', 'N'), help='output file prefix')
    p.add_argument('--spindle-speed', type=int, default=_d('spindle_speed', 10000), help='spindle speed S value (rpm or PWM). If set, emits M3 S<value> at start of G-code')
    p.add_argument('--feed', type=float, default=_d('feed', 1200.0), help='feed rate in mm/min (F value for G1 moves)')
    p.add_argument('--plunge', type=float, default=_d('plunge', 300.0), help='plunge feed rate in mm/min (F value for Z plunges)')
    p.add_argument('--gap', type=float, default=_d('gap', 0.0), help='inter-segment gap in mm (overrides default t*0.5)')
    p.add_argument('--overlap', type=float, default=_d('overlap', 2.0), help='positive value to let segments overlap (mm) to close chamfer gaps')
    p.add_argument('--hgap', type=float, default=_d('hgap', 1.0), help='vertical shift for vertical segments: move F/B down by hgap and E/C up by hgap (mm)')
    p.add_argument('--vert-length', type=float, default=_d('vert_length', 5.0), help='adjustment (mm) to vertical lengths of F,B,E,C; negative reduces length (e.g. -1 reduces by 1mm)')
    p.add_argument('--hort-length', type=float, default=_d('hort_length', 50.0), help='override horizontal length for segments A,G,D in mm (optional)')
    p.add_argument('--allow-vertical-overlap', dest='allow_vertical_overlap', action='store_true', help='allow vertical segments to grow beyond gaps and overlap horizontals (default: enabled)')
    p.add_argument('--no-allow-vertical-overlap', dest='allow_vertical_overlap', action='store_false', help='disable vertical overlap; clamp vertical lengths to available gaps')
    p.set_defaults(allow_vertical_overlap=_d('allow_vertical_overlap', True))
    p.add_argument('--render-source', choices=['poly','rect'], default=_d('render_source', 'poly'), help='Render SVG/WEBP from chamfer polygons (poly) or from rectangular segment params (rect)')
    p.add_argument('--pause-after-seg', action='store_true', default=_d('pause_after_seg', False), help='Pause after finishing each segment: raise Z to safe and emit M0 to allow tool clearing/replacement')
    p.add_argument('--debug-gcode', action='store_true', default=_d('debug_gcode', False), help='Emit parenthesized G-code comments for debugging (default: off)')
    p.add_argument('--use-shapely', action='store_true', default=_d('use_shapely', False), help='Force use of Shapely union (requires shapely)')
    p.add_argument('--no-shapely', action='store_true', default=_d('no_shapely', False), help='Disable Shapely union even if available')
    p.add_argument('--rotate', dest='rotate', action='store_true', help='Rotate output G-code by 90 degrees (default)')
    p.add_argument('--no-rotate', dest='rotate', action='store_false', help='Do not rotate output G-code')
    p.set_defaults(rotate=_d('rotate', True))
    return p.parse_args()


def write_image(filename, W, H, segments, margin=10, scale=8, bg=(255,255,255), segcolor=(0,0,0), render_source='poly', show_board=False, board_w=None, board_h=None, rotate=False, board_outline='dashed', show_centers=True, rect_segments=None):
    if not _HAS_PIL:
        raise RuntimeError('Pillow not available; install with pip install pillow to generate webp image')
    px_w = int((W + 2*margin) * scale)
    px_h = int((H + 2*margin) * scale)
    img = Image.new('RGB', (px_w, px_h), color=bg)
    draw = ImageDraw.Draw(img)
    # font for labels
    try:
        font = ImageFont.load_default()
    except Exception:
        font = None

    def _draw_dashed(x1, y1, x2, y2, dash=8, gap=6, fill=(0,0,0), width=1):
        dx = x2 - x1
        dy = y2 - y1
        dist = math.hypot(dx, dy)
        if dist <= 0:
            return
        ux = dx / dist
        uy = dy / dist
        pos = 0.0
        while pos < dist:
            seg_end = min(pos + dash, dist)
            sx = x1 + ux * pos
            sy = y1 + uy * pos
            ex = x1 + ux * seg_end
            ey = y1 + uy * seg_end
            draw.line([(sx, sy), (ex, ey)], fill=fill, width=width)
            pos += dash + gap

    # draw dashed border around digit
    bx1, by1 = margin*scale, margin*scale
    bx2, by2 = (margin+W)*scale, (margin+H)*scale
    border_stroke = max(1, int(scale/6))
    border_dash = max(6, int(scale*1.5))
    border_gap = max(8, int(scale*2.5))
    _draw_dashed(bx1, by1, bx2, by1, dash=border_dash, gap=border_gap, fill=(0,0,0), width=border_stroke)
    _draw_dashed(bx2, by1, bx2, by2, dash=border_dash, gap=border_gap, fill=(0,0,0), width=border_stroke)
    _draw_dashed(bx2, by2, bx1, by2, dash=border_dash, gap=border_gap, fill=(0,0,0), width=border_stroke)
    _draw_dashed(bx1, by2, bx1, by1, dash=border_dash, gap=border_gap, fill=(0,0,0), width=border_stroke)

    if rotate:
        def _tx(x, y):
            return (H - y, x)
    else:
        def _tx(x, y):
            return (x, y)

    for seg in segments:
        poly = seg.get('poly')
        if render_source == 'poly' and poly:
            transformed = [_tx(x, y) for (x, y) in poly]
            pts_scaled = [((margin + x) * scale, (margin + y) * scale) for (x, y) in transformed]
            draw.polygon(pts_scaled, fill=segcolor)
        else:
            pts = chamfer_rect_points(seg['x'], seg['y'], seg['w'], seg['h'], seg.get('r', 0))
            transformed = [_tx(x, y) for (x, y) in pts]
            pts_scaled = [((margin + x) * scale, (margin + y) * scale) for (x, y) in transformed]
            draw.polygon(pts_scaled, fill=segcolor)

    if show_board and (board_w is not None) and (board_h is not None):
        off_x = -((board_w - W) / 2.0)
        off_y = -((board_h - H) / 2.0)
        bp = [(off_x, off_y), (off_x + board_w, off_y), (off_x + board_w, off_y + board_h), (off_x, off_y + board_h)]
        transformed = [_tx(x, y) for (x, y) in bp]
        pts_scaled = [((margin + x) * scale, (margin + y) * scale) for (x, y) in transformed]
        outline_color = (255, 0, 0)
        stroke_w = max(1, int(scale / 6))
        dash_len = max(4, int(scale * 1.5))
        gap_len = max(6, int(scale * 2.5))
        if board_outline == 'dashed':
            for a, b in zip(pts_scaled, pts_scaled[1:]+[pts_scaled[0]]):
                _draw_dashed(a[0], a[1], b[0], b[1], dash=dash_len, gap=gap_len, fill=outline_color, width=stroke_w)
        else:
            for a, b in zip(pts_scaled, pts_scaled[1:]+[pts_scaled[0]]):
                draw.line([a, b], fill=outline_color, width=stroke_w)
        tlx, tly = pts_scaled[0]
        label = f"{board_w:.1f} x {board_h:.1f} mm"
        text_pos = (int(tlx) + 6, int(tly) + 6)
        draw.text(text_pos, label, fill=outline_color)

    # overlay centerlines/markers/labels when rect_segments available and enabled
    if rect_segments is not None and show_centers:
        # runtime hint for debugging whether overlay will be rendered
        try:
            print("[Make7Segment] overlay: drawing center markers and labels")
        except Exception:
            pass
        lookup = {s.get('name'): s for s in rect_segments}
        markers = []
        if 'A' in lookup:
            A = lookup['A']
            markers.append(('A', (A['x'] + A['w']/2.0, A.get('center_y', A['y'] + A['h']/2.0))))
        if 'G' in lookup:
            G = lookup['G']
            markers.append(('G', (G['x'] + G['w']/2.0, G.get('center_y', G['y'] + G['h']/2.0))))
        if 'D' in lookup:
            D = lookup['D']
            markers.append(('D', (D['x'] + D['w']/2.0, D.get('center_y', D['y'] + D['h']/2.0))))
        if 'F' in lookup:
            F = lookup['F']
            markers.append(('F', (F['x'] + F['w']/2.0, F.get('center_y', F['y'] + F['h']/2.0))))
        if 'B' in lookup:
            B = lookup['B']
            markers.append(('B', (B['x'] + B['w']/2.0, B.get('center_y', B['y'] + B['h']/2.0))))
        if 'E' in lookup:
            E = lookup['E']
            markers.append(('E', (E['x'] + E['w']/2.0, E.get('center_y', E['y'] + E['h']/2.0))))
        if 'C' in lookup:
            C = lookup['C']
            markers.append(('C', (C['x'] + C['w']/2.0, C.get('center_y', C['y'] + C['h']/2.0))))

        for label, (mx, my) in markers:
            tx, ty = _tx(mx, my)
            ix = int((margin + tx) * scale)
            iy = int((margin + ty) * scale)
            _draw_dashed(0, iy, img.width, iy, dash=max(6, int(scale*1.5)), gap=max(8, int(scale*2.0)), fill=(0,160,0), width=max(1, int(scale/6)))
            r = max(2, int(scale/4))
            draw.ellipse((ix-r, iy-r, ix+r, iy+r), fill=(0,0,255))
            try:
                lab = f"{fr(mx)},{fr(my)} mm"
            except Exception:
                lab = f"{mx:.3f},{my:.3f} mm"
            pad = max(12, int(scale * 1.5))
            if font is not None:
                try:
                    text_w, text_h = font.getsize(lab)
                except Exception:
                    text_w, text_h = (len(lab) * 6, 10)
            else:
                text_w, text_h = (len(lab) * 6, 10)
            text_x = ix + pad
            if text_x + text_w > img.width - 4:
                text_x = ix - text_w - pad
            text_y = iy - (text_h // 2)
            draw.rectangle((text_x-2, text_y-1, text_x+text_w+2, text_y+text_h+1), fill=(255,255,255))
            if font is not None:
                draw.text((text_x, text_y), lab, fill=(0,0,0), font=font)
            else:
                draw.text((text_x, text_y), lab, fill=(0,0,0))

        # Draw numbered corner labels for segment F (red) to inspect turn coordinates
        if 'F' in lookup:
            Fseg = lookup['F']
            f_pts = chamfer_rect_points(Fseg['x'], Fseg['y'], Fseg['w'], Fseg['h'], Fseg.get('r', 0))
            f_trans = [_tx(x, y) for (x, y) in f_pts]
            f_scaled = [((margin + x) * scale, (margin + y) * scale) for (x, y) in f_trans]
            for i, (px, py) in enumerate(f_scaled, start=1):
                # small red label with white background for readability
                lab = str(i)
                if font is not None:
                    try:
                        tw, th = font.getsize(lab)
                    except Exception:
                        tw, th = (len(lab) * 6, 10)
                else:
                    tw, th = (len(lab) * 6, 10)
                lx = int(px + max(6, int(scale*0.75)))
                ly = int(py - (th // 2))
                draw.rectangle((lx-2, ly-1, lx+tw+2, ly+th+1), fill=(255,255,255))
                if font is not None:
                    draw.text((lx, ly), lab, fill=(255,0,0), font=font)
                else:
                    draw.text((lx, ly), lab, fill=(255,0,0))

    img.save(filename, format='WEBP')


if __name__ == '__main__':
    # Determine profile path: CLI --profile wins, otherwise try ./profile.cfg
    # Load profile first so parse_args() can consult PROFILE_DEFAULTS if needed.
    cli_profile = None
    # Quick pre-scan for --profile on argv to allow defaults to be set from it
    import sys
    for idx, a in enumerate(sys.argv[1:], start=1):
        # handle `--profile file.cfg` form
        if a == '--profile' and (idx + 1) < len(sys.argv):
            cli_profile = sys.argv[idx + 1]
            break
        # handle `--profile=file.cfg` form
        if a.startswith('--profile='):
            cli_profile = a.split('=', 1)[1]
            break

    profile_path = cli_profile or ('profile.cfg' if os.path.exists('profile.cfg') else None)
    PROFILE_DEFAULTS.clear()
    if profile_path:
        pd = load_profile(profile_path)
        PROFILE_DEFAULTS.update(pd)
    args = parse_args()

    # expose chosen profile name in summary
    chosen_profile = profile_path or 'none'
    H = args.height
    W = args.width
    t = args.stroke
    r = args.radius

    segments = make_segments(W, H, t, r, gap=args.gap, overlap=args.overlap, hgap=args.hgap, vert_length=args.vert_length, hort_length=args.hort_length, allow_vertical_overlap=args.allow_vertical_overlap)
    for seg in segments:
        seg['poly'] = chamfer_rect_points(seg['x'], seg['y'], seg['w'], seg['h'], seg.get('r', 0))

    # Print debug coordinates for segment F (chamfer corner points) to help diagnose sizes
    F_debug = None
    for seg in segments:
        if seg.get('name') == 'F':
            F_debug = seg
            break
    if F_debug is not None:
        pts = F_debug.get('poly', [])
        if pts:
            print('\nSegment F chamfer corner coordinates (model mm):')
            for i, (px, py) in enumerate(pts, start=1):
                print(f"  P{i}: x={px:.3f}, y={py:.3f}")
            # compute distances per your definition
            # P2->P6 vertical distance
            if len(pts) >= 6:
                y2 = pts[1][1]
                y6 = pts[5][1]
                dist_2_6 = abs(y2 - y6)
            else:
                dist_2_6 = float('nan')
            # P3->P4 vertical distance
            if len(pts) >= 4:
                y3 = pts[2][1]
                y4 = pts[3][1]
                dist_3_4 = abs(y3 - y4)
            else:
                dist_3_4 = float('nan')
            total = dist_2_6 + dist_3_4
            centerline_y = (y2 + y6) / 2.0 if len(pts) >= 6 else float('nan')
            print(f"\nComputed distances for segment F:")
            print(f"  P2->P6 vertical = {dist_2_6:.3f} mm")
            print(f"  P3->P4 vertical = {dist_3_4:.3f} mm")
            print(f"  Sum = {total:.3f} mm")
            print(f"  Centerline Y (mid of P2 and P6) = {centerline_y:.3f} mm")
            print(f"  Segment F rect height (h) = {F_debug.get('h'):.3f} mm\n")

    if args.use_shapely and args.no_shapely:
        print("Conflicting options: --use-shapely and --no-shapely both set; ignoring shapely flags and auto-detecting.")
        use_shapely = _HAS_SHAPELY
    elif args.use_shapely:
        use_shapely = True
    elif args.no_shapely:
        use_shapely = False
    else:
        use_shapely = _HAS_SHAPELY

    out_segments = None
    if use_shapely:
        if not _HAS_SHAPELY:
            print("Shapely requested but not available; falling back to per-segment polygons. Install shapely to enable union.")
            use_shapely = False
        else:
            polys = []
            for seg in segments:
                p = seg.get('poly')
                if p and len(p) >= 3:
                    polys.append(Polygon(p))
            merged = unary_union(polys) if polys else None
            if merged is not None and box is not None:
                try:
                    merged = merged.intersection(box(0.0, 0.0, W, H))
                except Exception:
                    pass
            merged_polys = []
            if merged is None:
                merged_polys = []
            elif merged.geom_type == 'Polygon':
                merged_polys = [merged]
            elif merged.geom_type == 'MultiPolygon':
                merged_polys = list(merged.geoms)
            else:
                print('Unexpected result from shapely union:', getattr(merged, 'geom_type', type(merged)))
                merged_polys = []
            out_segments = []
            for mp in merged_polys:
                coords = list(mp.exterior.coords)
                if len(coords) > 1 and coords[0] == coords[-1]:
                    coords = coords[:-1]
                out_segments.append({'poly': coords})

    if out_segments is None:
        out_segments = []
        for seg in segments:
            p = seg.get('poly')
            if p:
                out_segments.append({'poly': p})
            else:
                out_segments.append({'x': seg['x'], 'y': seg['y'], 'w': seg['w'], 'h': seg['h'], 'r': seg.get('r', 0)})

    prefix = args.outprefix or f"N"
    svgfn = prefix + ".svg"
    gfn = prefix + ".gcode"
    print(f"Preparing outputs {svgfn} and {gfn} with H={H} W={W} t={t} r={r}")

    if args.depth is not None:
        cut_depth = float(args.depth)
    else:
        cut_depth = float(args.board_thickness)
    if args.passdepth is not None:
        pass_depth = float(args.passdepth)
        paths = max(1, int(math.ceil(cut_depth / pass_depth)))
    else:
        paths = max(1, int(args.cutting_paths))
        pass_depth = float(cut_depth) / float(paths)

    margin = 10
    board_h = float(args.board_height)
    if args.board_width is not None:
        board_w = float(args.board_width)
    else:
        board_w = W + 2.0 * margin

    print(f"\nBoard dimension (WxH): {board_w:.3f} mm x {board_h:.3f} mm (margin {margin} mm)")
    print(f"Digit dimension (WxH): {W:.3f} mm x {H:.3f} mm")

    print("\nRun parameters:")
    print(f"  - Profile: {chosen_profile}")
    print(f"  - Output prefix: {prefix}")
    print(f"  - Bit diameter: {args.bit:.3f} mm")
    print(f"  - Cut depth: {cut_depth:.3f} mm")
    print(f"  - Depth per pass: {pass_depth:.3f} mm")
    print(f"  - Number of passes: {paths}")
    print(f"  - Feed (XY): {args.feed:.3f} mm/min")
    print(f"  - Plunge (Z): {args.plunge:.3f} mm/min")
    print(f"  - Spindle speed: {args.spindle_speed if args.spindle_speed is not None else 'OFF'}")
    print(f"  - Rotate G-code: {'yes' if args.rotate else 'no'}")
    print(f"  - Vertical length adjust: {args.vert_length} mm")
    print(f"  - show-board-dim: {'enabled' if args.show_board_dim else 'disabled'}")

    print(f"Board thickness: {cut_depth:.3f} mm")
    print(f"Number of passes: {paths}")
    print(f"Depth per pass: {pass_depth:.3f} mm")
    print("Pass targets (cumulative Z):")
    for i in range(paths):
        cum_z = -((i + 1) * pass_depth)
        print(f"  - Pass {i+1}: Z = {cum_z:.3f} mm")

    if args.show_board_dim:
        pass_depth = float(cut_depth)
        print("\nshow-board-dim enabled: using single demo pass for G-code preview")
        print("Updated Number of passes: 1")

    write_svg(svgfn, W, H, out_segments, margin=margin, show_board=args.show_board_dim, board_w=board_w, board_h=board_h, render_source=args.render_source)
    write_gcode(gfn, W, H, out_segments, bit_dia=args.bit, cut_depth=cut_depth, pass_depth=pass_depth, feed=args.feed, plunge=args.plunge, show_board=args.show_board_dim, board_w=board_w, board_h=board_h, margin=margin, rotate=args.rotate, spindle_speed=args.spindle_speed, pause_after_segment=args.pause_after_seg, debug_gcode=args.debug_gcode)

    if _HAS_PIL:
        imgfn = prefix + ".webp"
        try:
            write_image(imgfn, W, H, out_segments, margin=margin, render_source=args.render_source, show_board=args.show_board_dim, board_w=board_w, board_h=board_h, rotate=False, board_outline=args.board_outline, show_centers=args.debug_centers, rect_segments=segments)
            print(f"Wrote image: {imgfn}")
        except Exception as e:
            print("Image export failed:", e)

    print("Done.")
