#!/usr/bin/env python3
"""
Make7SegmentShapely.py

Copy of Make7Segment.py with shapely-based polygon union to remove seams.

Usage:
  python Make7SegmentShapely.py

Requires: shapely (pip install shapely)
"""
import sys
import math
import argparse
from xml.sax.saxutils import escape

try:
    from shapely.geometry import Polygon, box
    from shapely.ops import unary_union
except Exception:
    Polygon = None
    unary_union = None
    box = None


def fr(x):
    return f"{x:.3f}"


def rect_svg(x, y, w, h, rx, fill="none", stroke="#000", stroke_width=1):
    return f'<rect x="{fr(x)}" y="{fr(y)}" width="{fr(w)}" height="{fr(h)}" rx="{fr(rx)}" fill="{fill}" stroke="{stroke}" stroke-width="{fr(stroke_width)}" />\n'


def write_svg(filename, W, H, segments, margin=10):
    vw = W + 2 * margin
    vh = H + 2 * margin
    with open(filename, "w") as f:
        f.write('<?xml version="1.0" encoding="UTF-8"?>\n')
        f.write(f'<svg xmlns="http://www.w3.org/2000/svg" width="{fr(vw)}mm" height="{fr(vh)}mm" viewBox="0 0 {fr(vw)} {fr(vh)}">\n')
        f.write('<g transform="translate(%s,%s)">\n' % (fr(margin), fr(margin)))
        f.write(rect_svg(0, 0, W, H, 0, fill="#fff", stroke="#888", stroke_width=0.5))
        for seg in segments:
            poly = seg.get('poly')
            if poly:
                pts = " ".join([f"{fr(x)},{fr(y)}" for (x, y) in poly])
                f.write(f'<polygon points="{escape(pts)}" fill="#111" stroke="#000" stroke-width="0.5" />\n')
            else:
                f.write(rect_svg(seg['x'], seg['y'], seg['w'], seg['h'], seg.get('r',0), fill="#ffcccc", stroke="#800" , stroke_width=0.8))
        f.write('</g>\n')
        f.write('</svg>\n')


def write_gcode(filename, W, H, segments, bit_dia=3.0, cut_depth=3.0, pass_depth=1.5, feed=800, plunge=300, safe_z=5.0):
    with open(filename, "w") as f:
        f.write("(Simple 7-seg outline generated by Make7SegmentShapely.py)\n")
        f.write("G21 (mm)\nG90 (absolute)\nG17\n")
        f.write(f"F{feed}\n")
        depth = cut_depth
        passes = max(1, int(math.ceil(depth / pass_depth)))
        pass_step = depth / passes
        for i in range(passes):
            cur_depth = -(i + 1) * pass_step
            f.write(f"(pass {i+1}/{passes} to Z{fr(cur_depth)})\n")
            for seg in segments:
                poly = seg.get('poly')
                if not poly:
                    x0 = seg['x']
                    y0 = seg['y']
                    w = seg['w']
                    h = seg['h']
                    poly = [(x0, y0), (x0+w, y0), (x0+w, y0+h), (x0, y0+h)]
                f.write(f"G0 Z{fr(safe_z)}\n")
                f.write(f"G0 X{fr(poly[0][0])} Y{fr(poly[0][1])}\n")
                f.write(f"G1 Z{fr(cur_depth)} F{plunge}\n")
                for (cx, cy) in poly[1:]+[poly[0]]:
                    f.write(f"G1 X{fr(cx)} Y{fr(cy)} F{feed}\n")
                f.write(f"G0 Z{fr(safe_z)}\n")
        f.write("M5\nG0 X0 Y0\n")


# Chamfer polygon helper
def chamfer_rect_points(x, y, w, h, c):
    c = min(c, w/2.0, h/2.0)
    pts = []
    pts.append((x + c, y))
    pts.append((x + w - c, y))
    pts.append((x + w, y + c))
    pts.append((x + w, y + h - c))
    pts.append((x + w - c, y + h))
    pts.append((x + c, y + h))
    pts.append((x, y + h - c))
    pts.append((x, y + c))
    return pts


def make_segments(W, H, t, r, gap=None, overlap=0.0, hgap=0.0):
    s = gap if (gap is not None) else (t * 0.5)
    ov = max(0.0, float(overlap))
    hg = float(hgap) if (hgap is not None) else 0.0
    Lh = W - 2*t + 2.0 * ov
    if Lh <= 0:
        raise ValueError("Computed invalid segment dimensions; check stroke vs overall size.")
    segments = []
    base_Ay = s
    Ay = base_Ay + 1.0 * hg
    base_Dy = H - s - t
    Dy = base_Dy - hg
    A_bottom = base_Ay + t
    D_top_orig = base_Dy
    if D_top_orig <= A_bottom + 0.001:
        raise ValueError("Not enough vertical space for middle segment; reduce stroke or margins.")
    center_mid = (A_bottom + Dy) / 2.0
    Gy = center_mid - (t / 2.0)
    G_mid = Gy + (t / 2.0)
    # compute top vertical using original A bottom so moving A doesn't shorten them
    orig_A_bottom = base_Ay + t
    top_end = G_mid - hg
    Lv_top = top_end - orig_A_bottom
    if Lv_top < 0:
        Lv_top = 0.0
    top_vert_y = orig_A_bottom
    # bottom verticals anchored to original D top so their length stays constant
    bot_vert_y = G_mid + hg
    Lv_bot = D_top_orig - bot_vert_y
    if Lv_bot < 0:
        Lv_bot = 0.0
    # segments
    segments.append({'name':'A', 'x': (W - Lh)/2.0, 'y': Ay, 'w': Lh, 'h': t, 'r': r})
    Fx = (W - Lh)/2.0 - (t/2.0)
    Bx = (W + Lh)/2.0 - (t/2.0)
    segments.append({'name':'F', 'x': Fx, 'y': top_vert_y, 'w': t, 'h': Lv_top, 'r': r})
    segments.append({'name':'B', 'x': Bx, 'y': top_vert_y, 'w': t, 'h': Lv_top, 'r': r})
    segments.append({'name':'G', 'x': (W - Lh)/2.0, 'y': Gy, 'w': Lh, 'h': t, 'r': r})
    segments.append({'name':'E', 'x': Fx, 'y': bot_vert_y, 'w': t, 'h': Lv_bot, 'r': r})
    segments.append({'name':'C', 'x': Bx, 'y': bot_vert_y, 'w': t, 'h': Lv_bot, 'r': r})
    segments.append({'name':'D', 'x': (W - Lh)/2.0, 'y': Dy, 'w': Lh, 'h': t, 'r': r})
    return segments


def parse_args():
    p = argparse.ArgumentParser()
    p.add_argument('--height', type=float, default=200.0, help='digit height in mm')
    p.add_argument('--width', type=float, default=110.0, help='digit width in mm')
    p.add_argument('--stroke', type=float, default=20.0, help='segment thickness in mm')
    p.add_argument('--radius', type=float, default=10.0, help='corner radius in mm')
    p.add_argument('--bit', type=float, default=3.0, help='cutter diameter in mm')
    p.add_argument('--depth', type=float, default=3.0, help='cut depth in mm')
    p.add_argument('--passdepth', type=float, default=1.5, help='depth per pass in mm')
    p.add_argument('--outprefix', type=str, default=None, help='output file prefix')
    p.add_argument('--gap', type=float, default=0.0, help='inter-segment gap in mm (overrides default t*0.5)')
    p.add_argument('--overlap', type=float, default=4.0, help='positive value to let segments overlap (mm) to close chamfer gaps')
    p.add_argument('--hgap', type=float, default=5.0, help='vertical shift for vertical segments: move A/D and verticals relative to G (mm)')
    return p.parse_args()


def main():
    args = parse_args()
    H = args.height
    W = args.width
    t = args.stroke
    r = args.radius
    segments = make_segments(W, H, t, r, gap=args.gap, overlap=args.overlap, hgap=args.hgap)
    # precompute chamfered polygons
    for seg in segments:
        seg['poly'] = chamfer_rect_points(seg['x'], seg['y'], seg['w'], seg['h'], seg.get('r', 0))

    if Polygon is None:
        print("Shapely not available. Install with: pip install shapely")
        sys.exit(1)

    # convert to shapely polygons and union
    polys = []
    for seg in segments:
        p = seg.get('poly')
        if p and len(p) >= 3:
            polys.append(Polygon(p))
    merged = unary_union(polys)
    # Clip result to the board extents to avoid tiny expansion beyond W/H
    if box is not None:
        try:
            merged = merged.intersection(box(0.0, 0.0, W, H))
        except Exception:
            pass

    merged_polys = []
    if merged.geom_type == 'Polygon':
        merged_polys = [merged]
    elif merged.geom_type == 'MultiPolygon':
        merged_polys = list(merged.geoms)
    else:
        print('Unexpected result from union:', merged.geom_type)
        sys.exit(1)

    out_segments = []
    for mp in merged_polys:
        coords = list(mp.exterior.coords)
        if len(coords) > 1 and coords[0] == coords[-1]:
            coords = coords[:-1]
        out_segments.append({'poly': coords})

    prefix = args.outprefix or f"Make7Segment_H{int(H)}_W{int(W)}_shapely"
    svgfn = prefix + ".svg"
    gfn = prefix + ".gcode"
    print(f"Writing {svgfn} and {gfn} with H={H} W={W} t={t} r={r} (shapely unions)")
    write_svg(svgfn, W, H, out_segments)
    write_gcode(gfn, W, H, out_segments, bit_dia=args.bit, cut_depth=args.depth, pass_depth=args.passdepth)
    print("Done.")

if __name__ == '__main__':
    main()
